### ISSUE TITLE
README.md sample code fails with ImportError: cannot import name 'Alias' from 'alaska' 

### ISSUE THREAD

**Issue by dcslagel** [FRI-Energy-Analytics/alaska#12]
**Describe the bug**
Running  sample code in the README's 'Sample Usage' section fails with the import error: `ImportError: cannot import name 'Alias' from 'alaska' 

**To Reproduce**
1. Create a python virtual environment and activate it.

2. install Alaska, `pip install alaska`

3. Save the Sample Usage code to a script:
```python
from alaska import Alias
from welly import Project
import lasio

path = "testcase.las"
a = Alias()
parsed, not_found = a.parse(path)
```
4. run the script: (this will display the error)
```python sample-runner.py```

**Expected behavior**
The script should run successfully with no output

**Screenshots**
```
 python sample-runner.py 
Traceback (most recent call last):
  File "sample-runner.py", line 1, in <module>
    from alaska import Alias
ImportError: cannot import name 'Alias' from 'alaska' (unknown location)
```

**System (please complete the following information):**
 - OS: MacOS
 - Python version: 3.7
 - AlasKA Version: 0.0.2
 - PyTorch Version 1.6.0

**Additional context**
```bash

pip list
Package                       Version
----------------------------- ---------
AlasKA                        0.0.2
backports.functools-lru-cache 1.6.1
certifi                       2020.6.20
cycler                        0.10.0
future                        0.18.2
kiwisolver                    1.2.0
lasio                         0.28
matplotlib                    3.3.2
numpy                         1.19.2
pandas                        1.1.2
Pillow                        7.2.0
pip                           20.2.3
pyparsing                     2.4.7
python-dateutil               2.8.1
pytz                          2020.1
setuptools                    50.3.0
six                           1.15.0
torch                         1.6.0
```

**Comment by jessepisel** [comment]
Thanks for opening the issue @dcslagel . I was able to reproduce the error on two different machines. I have gone through and reorganized the package today and was able to get it to function correctly on both linux and windows. We are going to have version 0.0.3 out by the end of this week which should take care of this issue. I will leave this issue open until we have the new version on PyPi

**Comment by dcslagel** [comment]
@jessepisel,  Great,  I'll look for 0.0.3 later this week.  Thanks.

**Comment by jessepisel** [comment]
I think this should be taken care of with PR #15

**Comment by dcslagel** [comment]
@jessepisel,  Yes, I just tested it with both a git-repo clone and by install ing AlasKA 0.0.4.  This issue is resolved in both cases.

Thank you,
DC
