### ISSUE TITLE
keyword extractor counter

### ISSUE THREAD

**Issue by jessepisel** [FRI-Energy-Analytics/alaska#16]
**Describe the bug**
running the parser on `testcase1.las` it returns `Aliased -1 mnemonics with keyword extractor`

**To Reproduce**
``` python
from alaska import Alias
path = "alaska/data/testcase1.las"
a = Alias(model=False)
parsed, not_found = a.parse(path)
```

**Expected behavior**
should print 1 mnemonic aliased with keyword extractor

**Screenshots**

**System (please complete the following information):**
 - OS: windows
 - Python version 3.7
 - AlasKA Version 0.0.4
 - PyTorch Version 1.2

**Additional context**

**Comment by dcslagel** [comment]
Just double checking the expected behavior for:

```python
from alaska import Alias
path = "alaska/data/testcase1.las"
a = Alias(model=False)
parsed, not_found = a.parse(path)
```

I am seeing the dictionary_parse() run and find all aliases before keyword_parse() is called.  Is that at the expected behavior.  If so then should keyword_parse() report 0 mnemonics aliased with keyword_extractor instead of 1?

Thanks,
DC

**Comment by dingdonged** [comment]
keyword_parse() should indeed return 0 instead of -1
