### ISSUE TITLE
Pypi: alaska-0.0.4 pkg: ModuleNotFoundError: No module named 'predict_from_model' 

### ISSUE THREAD

**Issue by dcslagel** [FRI-Energy-Analytics/alaska#38]
**Describe the bug**
After creating a virtualenv and installing alaska-0.0.4 (current version on https://pypi.org) with pip, attempts to import alaska fail with the error msg: ` ModuleNotFoundError: No module named 'predict_from_model' `.  It looks like this is a very early version of Alaska and releasing the current version to https://pypi.org might solve the problem.  

**To Reproduce**
1. python -m venv venv-pypi-alaska
2. source venv-pypi-alaska/bin/activate
3. pip install --no-cache-dir alaska
4. python
5. `>>> import alaska`
6. output:
```python
>>> import alaska
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv-pypy-alaska/lib/python3.8/site-packages/alaska/__init__.py", line 1, in <module>
    from .keyword_tree import Alias, search, make_tree, search_child
  File ".../venv-pypy-alaska/lib/python3.8/site-packages/alaska/keyword_tree.py", line 7, in <module>
    from predict_from_model import make_prediction
ModuleNotFoundError: No module named 'predict_from_model'
```

**Expected behavior**
Import alaska and return to python prompt `>>>`

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: MacOS
 - Python version 3.8
 - AlasKA Version 0.0.4
 - PyTorch Version 1.7.0

**Additional context**

**Comment by dcslagel** [comment]
@jessepisel , Should a more current version of Alaska  be posted to https://pypi.org/project/alaska/ ?   The latest version on PyPi is 0.0.4 which has this bug in it and the current version is 0.5.

DC

**Comment by jessepisel** [comment]
I think the main issue is that installing from PyPi removes the top level `utils.py` file (#67). I think if we remove the package from PyPi that might be the best option. What do you think @dingdonged ?
