### ISSUE TITLE
IndexError: tutorial/parse.py

### ISSUE THREAD

**Issue by dcslagel** [FRI-Energy-Analytics/alaska#41]
**Describe the bug**
running `python tutorial/parse.py fails with the following error:
```python
IndexError: index 0 is out of bounds for axis 0 with size 0
```
**To Reproduce**
1. clone the alaska repo
2. cd alaska
3. pip install -e .
4. pip install welly
5. python tutorials/parse.py
6. output
```python
...
Traceback (most recent call last):
  File "tutorials/parse.py", line 45, in <module>
    p = Project.from_las(path)
  File "/usr/local/devel/MyWrk/geo-wrk/alaska/tmp-alaska/venv-tmp/lib/python3.8/site-packages/welly/project.py", line 139, in from_las
    list_of_Wells = [Well.from_las(f, remap=remap, funcs=funcs, 
  File "/usr/local/devel/MyWrk/geo-wrk/alaska/tmp-alaska/venv-tmp/lib/python3.8/site-packages/welly/project.py", line 139, in <listcomp>
    list_of_Wells = [Well.from_las(f, remap=remap, funcs=funcs, 
  File "/usr/local/devel/MyWrk/geo-wrk/alaska/tmp-alaska/venv-tmp/lib/python3.8/site-packages/welly/well.py", line 304, in from_las
    return cls.from_lasio(las,
  File "/usr/local/devel/MyWrk/geo-wrk/alaska/tmp-alaska/venv-tmp/lib/python3.8/site-packages/welly/well.py", line 210, in from_lasio
    if l_index[0] < l_index[1]:
IndexError: index 0 is out of bounds for axis 0 with size 0
0it [00:00, ?it/s]
```

**Expected behavior**
Print the parsed data from welly.Project and display a heat map.

**Screenshots**
N/A

**System (please complete the following information):**
- OS: Darwin
 - Python version Python 3.8.6 
 - AlasKA Version 0.3b0+42.g3bc970c
 - PyTorch Version 1.7.0

**Additional context**
N/A

**Comment by jessepisel** [comment]
Thanks for opening this up @dcslagel I think this might be an issue on the `Welly` side. They recently released a new version with some changes to the `from_las` function. It looks like they added an `index` argument that defaults to `None`. I will look into this this week.

**Comment by jessepisel** [comment]
I did a bit more digging into it this morning, and it looks like `Welly` is throwing the error because `testcase1.las` doesn't contain anything besides the header. It works fine with other LAS files, so I am tempted to add an example that contains more than just header info for this tutorial. What do you think @dcslagel ?

**Comment by dcslagel** [comment]
@jessepisel ,  

Yes, I agree with you:  "add an example that contains more than just header info for this tutorial."   The purpose of the tutorial is to help get a person up-to-speed with standard use cases so it makes sense to avoid unusual cases like header-only las files.  

DC

**Comment by jessepisel** [comment]
That sounds good. I am going to add a LAS file with data behind it. I tracked down this issue in `welly` and opened https://github.com/agile-geoscience/welly/issues/149 which should take care of it. I will put in a PR with the LAS file after the bug is fixed in `welly`

**Comment by jessepisel** [comment]
The `Welly` issue is closed, I am going to update this with a LAS file with data behind it later this week.
